yt-clone/routes/web.php
<?php

use App\Models\Channel;

use Illuminate\Support\Facades\Auth;
use App\Http\Livewire\Video\AllVideo;
use Illuminate\Support\Facades\Route;
use App\Http\Livewire\Video\EditVideo;
use App\Http\Livewire\Video\WatchVideo;
use App\Http\Controllers\HomeController;
use App\Http\Livewire\Video\CreateVideo;
use App\Http\Controllers\SearchController;
use App\Http\Controllers\ChannelController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    // if logged in -- channels that i subscribed to
    if( Auth::check() ) {
        $channels = Auth::user()->subscribedChannels()->with('videos')->get()->pluck('videos');
        // dd($channels);
    } else {
        // else all videos
        $channels = Channel::get()->pluck('videos');
    }

    return view('welcome', compact('channels'));
    
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::get('/test', function() {
    return view('test');
});

Route::middleware('auth')->group( function() {

    Route::get('/channel/{channel}/edit', [ChannelController::class, 'edit'])->name('channel.edit');
});

Route::middleware('auth')->group( function() {

    Route::get('/videos/{channel}/create', CreateVideo::class)->name('video.create');
    Route::get('/videos/{channel}/{video}/edit', EditVideo::class)->name('video.edit');
    Route::get('/allvideo/{channel}', AllVideo::class)->name('video.all');

});

Route::get('/watch/{video}', WatchVideo::class)->name('video.watch');
Route::get('/search/', [SearchController::class, 'search'])->name('search');

yt-clone/app/Models/Video.php
<?php

namespace App\Models;

use App\Models\Like;
use App\Models\Channel;

use App\Models\Comment;
use App\Models\Dislike;
use Illuminate\Support\Carbon;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class Video extends Model
{
    use HasFactory;

    protected $guarded = ['id'];

    public function getRouteKeyName()
    {
        return 'uid';
    }

    public function getThumbnailAttribute()
    {
        if($this->thumbnail_image) {
            return '/videos/' . $this->uid . '/' . $this->thumbnail_image;
        } else {
            return '/videos/' . 'default.png';
        }

    }

    public function getUploadedDateAttribute()
    {
        $d = new Carbon($this->created_at);
        return $d->toFormattedDateString();
    }

    public function channel()
    {
        return $this->belongsTo(Channel::class);
    }

    public function likes()
    {
        return $this->hasMany(Like::class);
    }

    public function dislikes()
    {
        return $this->hasMany(Dislike::class);
    }

    public function doesUserLikedVideo()
    {
        return $this->likes()->where('user_id', auth()->id())->exists();
    }

    public function doesUserDislikedVideo()
    {
        return $this->dislikes()->where('user_id', auth()->id())->exists();
    }

    public function comments()
    {
        return $this->hasMany(Comment::class)->whereNull('reply_id');
    }

    public function AllCommentsCount()
    {
        return $this->hasMany(Comment::class)->count();
    }

}

yt-clone/resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Dashboard') }}</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    {{ __('You are logged in!') }}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

yt-clone/resources/views/search.blade.php
@extends('layouts.app')

@section('content')
<div class="container">

    <div class="row my-4">
        @foreach ($videos as $video)

        <div class="col-12 ">

            <a href="{{ route('video.watch', $video)}}" class="card-link">
                <div class="card mb-4 " style="border:none;">

                    <div class="card-horizontal">
                        <div>
                            <img class="" src="{{asset( $video->thumbnail)}}" alt="Card image cap"
                                style="height: 100%; width:333px">
                        </div>
                        <div class="card-body">
                            <h4 class="ml-3">{{$video->title}}</h4>
                            <p class="text-gray font-weight-bold">{{ $video->views}} views •
                                {{$video->created_at->diffForHumans()}}</p>
                            <div class="d-flex align-items-center">
                                <img src="{{asset('/images/' . $video->channel->image)}}" class="rounded circle" width="50px">
                                <p class="text-gray font-weight-bold">
                                    {{ $video->channel->name}}
                                </p>

                            </div>
                            <p class="text-truncate">
                                {{$video->description}}
                            </p>


                        </div>
                    </div>
                </div>
            </a>

        </div>


        @endforeach
    </div>

</div>
@endsection